apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubecenter.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubecenter.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kubecenter.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  template:
    metadata:
      labels:
        {{- include "kubecenter.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: backend
    spec:
      serviceAccountName: {{ include "kubecenter.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: backend
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          ports:
            - name: http
              containerPort: {{ .Values.backend.port }}
              protocol: TCP
          env:
            - name: KUBECENTER_SERVER_PORT
              value: {{ .Values.backend.port | quote }}
            - name: KUBECENTER_DEV
              value: {{ .Values.backend.config.dev | quote }}
            - name: KUBECENTER_LOG_LEVEL
              value: {{ .Values.backend.config.logLevel | quote }}
            - name: KUBECENTER_LOG_FORMAT
              value: {{ .Values.backend.config.logFormat | quote }}
            - name: KUBECENTER_CLUSTERID
              value: {{ .Values.backend.config.clusterID | quote }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
