apiVersion: v2
name: kubecenter
description: A web-based Kubernetes management platform
type: application
version: 0.3.0
appVersion: "0.3.0"
keywords:
  - kubernetes
  - management
  - dashboard
maintainers:
  - name: KubeCenter
dependencies:
  - name: kube-prometheus-stack
    version: "~82.10"
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.deploy
    alias: monitoring-stack
  - name: postgresql
    version: "~16.4"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
